version: '2'

services:

    nginx:
        build: ./rev-proxy
        ports:
          - "8089:8080"
        networks:
          - internal-net

    web:
        build: ./web
        networks:
          - internal-net
          - db-net
    db:
        build: ./db
        networks:
          - db-net

networks:
    internal-net:
    db-net:
